// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83qQjhCk-FKOkZLcpAM5fOdPnL2ehAvM',
    appId: '1:852285088649:web:8cf76ccbca3aaee6da3758',
    messagingSenderId: '852285088649',
    projectId: 'generalstore-dd7a5',
    authDomain: 'generalstore-dd7a5.firebaseapp.com',
    storageBucket: 'generalstore-dd7a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkcqa1epwjAlwBE5OQ7mjDOgAS8cP3TAI',
    appId: '1:852285088649:android:662acd7c3f114075da3758',
    messagingSenderId: '852285088649',
    projectId: 'generalstore-dd7a5',
    storageBucket: 'generalstore-dd7a5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEeZc1etWccU0UcbQwXYu3qZNOh0wgDhU',
    appId: '1:852285088649:ios:8fafd6287ed3f3e3da3758',
    messagingSenderId: '852285088649',
    projectId: 'generalstore-dd7a5',
    storageBucket: 'generalstore-dd7a5.firebasestorage.app',
    iosClientId:
        '852285088649-1lt5o4fhr7f7ttd3upht3c6jfd55uhug.apps.googleusercontent.com',
    iosBundleId: 'com.example.generalstore',
  );
}
